name: doanmobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  salomon_bottom_bar: ^3.3.2
  firebase_core: ^4.2.0
  http: ^1.5.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  url_launcher: ^6.3.2
  video_player: ^2.10.0
  carousel_slider: ^5.1.1
  speech_to_text: ^7.3.0
  smooth_page_indicator: ^1.2.1
  flutter_rating_bar: ^4.0.1
  chewie: ^1.13.0
  youtube_player_flutter: ^9.1.3
  cloudinary_flutter: ^1.3.0
  cloudinary_public: ^0.23.1
  webview_flutter: ^4.13.0
  characters: ^1.4.0
  easy_localization: ^3.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/intro1.png
    - assets/logo.png
    - assets/translations/